site_name: Gen AI for Modern Workforce - Prompt Lib
site_url: https://warasinee-cha.github.io/genai4mf-prompt-lib/

theme:
  name: material
  palette:
    primary: amber
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 2

nav:
  - Home: index.md
  - Download Slides: slide.md
  - Fun Prompts: fun-prompts.md
  - Prompt Engineering:
    - Personalized Learning: pe-personalized-learning.md
    - English Communication: pe-english-communication.md
    - Creativity Boost: pe-creativity-boost.md
    - Writing Task: pe-writing-doc.md
    - Data Analytics: pe-data-analytics.md
  - Resources:
    - Generative AI: generative-ai-basics.md
    - NotebookLM : notebooklm.md
    - Canva AI Features: canva-ai.md
    - Gamma.app: gamma-app.md
    - Suno: suno-video.md
    - Luma AI: luma-ai-video.md
    - More Tools: additional-tool.md

extra_css:
  - stylesheets/extra.css

